rosrun mover2 mover_clbk.py 0
rosrun mover2 mover_clbk.py 1
rosrun mover2 mover_clbk.py 2
rosrun mover2 mover_clbk.py 3
rosrun mover2 mover_clbk.py 4
rosrun mover2 mover_clbk.py 5
rosrun mover2 mover_clbk.py 6
rosrun mover2 mover_clbk.py 7
rosrun mover2 mover_clbk.py 8
rosrun mover2 mover_clbk.py 9
rosrun mover2 mover_clbk.py 10
rosrun mover2 mover_clbk.py 11
rosrun mover2 mover_clbk.py 12
rosrun mover2 mover_clbk.py 13
rosrun mover2 mover_clbk.py 14
rosrun mover2 mover_clbk.py 15
